# Generated by Django 3.2.5 on 2021-07-30 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180626_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2021, 7, 30)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=147, primary_key=True, serialize=False, unique=True),
        ),
    ]
