# Generated by Django 3.2.5 on 2021-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_reg_info_usr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=54, primary_key=True, serialize=False, unique=True),
        ),
    ]
